export {default as Authentication} from './auth/Authntication'
export {default as Doctors} from './userControllers/doctors'
export {default as Bookings} from './userControllers/Bookings'
export {default as GetControllers} from './GetControllers.js'
export {default as UserPanel} from './UserPanel'
export {default as AdminController} from './AdminController'
